config/routes.rb
Rails.application.routes.draw do
  resource :home, only: [:show]

  resources :tickets
  resources :users
  resources :organizations

  root 'homes#show'
end

app/models/user.rb
class User < ApplicationRecord
  include SearchableModel

  belongs_to :organization, optional: true, counter_cache: true

  has_many :tag_lists, as: :taggable
  has_many :tags, through: :tag_lists

  has_many :assigned_tickets, foreign_key: "assignee_id", class_name: "Ticket"
  has_many :submitted_tickets, foreign_key: "submitter_id", class_name: "Ticket"

  def self.searchable_attributes
    @@_searchable_attributes ||= begin
      non_searchables = [
                          "id", "updated_at",
                          "assigned_tickets_count",
                          "submitted_tickets_count"
                        ]

      column_names - non_searchables  + [TAG_FIELD]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Searchable
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:organization, :tags)
                 .order(:_id)
                 .page params[:page]

    @users = search @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:_id, :url, :external_id, :name, :alias, :active, :verified, :shared, :locale, :timezone, :last_login_at, :email, :phone, :signature, :organization_id, :suspended, :role)
    end

    def set_model
      @model = User
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def submitted_tickets_link user
    link_to user.submitted_tickets_count, tickets_path(field: :submitter_id, value: user._id)
  end

  def assigned_tickets_link user
    link_to user.assigned_tickets_count, tickets_path(field: :assignee_id, value: user._id)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :_id %>
    <%= form.text_field :_id, id: :user__id %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :user_url %>
  </div>

  <div class="field">
    <%= form.label :external_id %>
    <%= form.text_field :external_id, id: :user_external_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :alias %>
    <%= form.text_field :alias, id: :user_alias %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :user_active %>
  </div>

  <div class="field">
    <%= form.label :verified %>
    <%= form.check_box :verified, id: :user_verified %>
  </div>

  <div class="field">
    <%= form.label :shared %>
    <%= form.check_box :shared, id: :user_shared %>
  </div>

  <div class="field">
    <%= form.label :locale %>
    <%= form.text_field :locale, id: :user_locale %>
  </div>

  <div class="field">
    <%= form.label :timezone %>
    <%= form.text_field :timezone, id: :user_timezone %>
  </div>

  <div class="field">
    <%= form.label :last_login_at %>
    <%= form.datetime_select :last_login_at, id: :user_last_login_at %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :user_phone %>
  </div>

  <div class="field">
    <%= form.label :signature %>
    <%= form.text_field :signature, id: :user_signature %>
  </div>

  <div class="field">
    <%= form.label :organization_id %>
    <%= form.text_field :organization_id, id: :user_organization_id %>
  </div>

  <div class="field">
    <%= form.label :suspended %>
    <%= form.check_box :suspended, id: :user_suspended %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role, id: :user_role %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= render 'shared/flash_notifications' %>
<%= render 'shared/search_bar' %>

<% if @users.exists? %>
  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Url</th>
        <th>External Id</th>
        <th>Name</th>
        <th>Alias</th>
        <th>Active</th>
        <th>Verified</th>
        <th>Shared</th>
        <th>Locale</th>
        <th>Timezone</th>
        <th>Last login at</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Signature</th>
        <th>Organization Id</th>
        <th>Suspended</th>
        <th>Role</th>
        <th>#Submitted Tickets</th>
        <th>#Assigned Tickets</th>
        <th>Tags</th>
        <th>Created at</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user._id %></td>
          <td><%= link_to :url, user.url %></td>
          <td><%= user.external_id %></td>
          <td><%= user.name %></td>
          <td><%= user.alias %></td>
          <td><%= user.active %></td>
          <td><%= user.verified %></td>
          <td><%= user.shared %></td>
          <td><%= user.locale %></td>
          <td><%= user.timezone %></td>
          <td><%= user.last_login_at %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
          <td><%= user.signature %></td>
          <td><%= organization_link user %></td>
          <td><%= user.suspended %></td>
          <td><%= user.role %></td>
          <td><%= submitted_tickets_link user %></td>
          <td><%= assigned_tickets_link user %></td>
          <td><%= tag_names user %></td>
          <td><%= user.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-records notification alert">
    No users available for given input.
  </div>
<% end %>

<br/>
<%= paginate @users %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @user._id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @user.url %>
</p>

<p>
  <strong>External:</strong>
  <%= @user.external_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @user.alias %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @user.verified %>
</p>

<p>
  <strong>Shared:</strong>
  <%= @user.shared %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @user.locale %>
</p>

<p>
  <strong>Timezone:</strong>
  <%= @user.timezone %>
</p>

<p>
  <strong>Last login at:</strong>
  <%= @user.last_login_at %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Signature:</strong>
  <%= @user.signature %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @user.organization %>
</p>

<p>
  <strong>Suspended:</strong>
  <%= @user.suspended %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>