config/routes.rb
Rails.application.routes.draw do
  resource :home, only: [:show]

  resources :tickets
  resources :users
  resources :organizations

  root 'homes#show'
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  include SearchableModel

  has_many :tag_lists, as: :taggable
  has_many :tags, through: :tag_lists

  belongs_to :submitter, class_name: 'User', counter_cache: :submitted_tickets_count
  belongs_to :assignee, class_name: 'User', optional: true, counter_cache: :assigned_tickets_count
  belongs_to :organization, optional: true, counter_cache: true

  enum ticket_type: %i(incident problem question task)
  enum priority: %i(low normal high urgent)
  enum status: %i(open pending hold solved closed)
  enum via: %i(web chat voice)

  def self.searchable_attributes
    @@_searchable_attributes ||= begin
      non_searchables = ["id", "updated_at"]

      column_names - non_searchables + [TAG_FIELD]
    end
  end

  def self.search_by(field, term)
    case field
    when "submitter_id", "assignee_id"
      if term.present?
        value = User.where(_id: term)
      else
        value = nil
      end

      where(field => value)
    else
      super(field, term)
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  include Searchable
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.includes(:submitter, :assignee, :organization, :tags)
                     .order(:status, priority: :desc)
                     .page params[:page]

    @tickets = search @tickets
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:_id, :url, :external_id, :type, :subject, :description, :priority, :status, :submitter_id, :assignee_id, :organization_id, :has_incidents, :due_at, :via)
    end

    def set_model
      @model = Ticket
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def submitter_link ticket
    submitter = ticket.submitter
    link_to "#{submitter._id} (#{submitter.name})", users_path(field: :_id, value: submitter._id)
  end

  def assignee_link ticket
     if assignee = ticket.assignee
       link_to "#{assignee._id} (#{assignee.name})", users_path(field: :_id, value: assignee._id)
     else
      "Unassigned"
     end
  end
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :_id %>
    <%= form.text_field :_id, id: :ticket__id %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :ticket_url %>
  </div>

  <div class="field">
    <%= form.label :external_id %>
    <%= form.text_field :external_id, id: :ticket_external_id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :ticket_type %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :ticket_subject %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :ticket_description %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.text_field :priority, id: :ticket_priority %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :ticket_status %>
  </div>

  <div class="field">
    <%= form.label :submitter_id %>
    <%= form.text_field :submitter_id, id: :ticket_submitter_id %>
  </div>

  <div class="field">
    <%= form.label :assignee_id %>
    <%= form.text_field :assignee_id, id: :ticket_assignee_id %>
  </div>

  <div class="field">
    <%= form.label :organization_id %>
    <%= form.text_field :organization_id, id: :ticket_organization_id %>
  </div>

  <div class="field">
    <%= form.label :has_incidents %>
    <%= form.text_field :has_incidents, id: :ticket_has_incidents %>
  </div>

  <div class="field">
    <%= form.label :due_at %>
    <%= form.datetime_select :due_at, id: :ticket_due_at %>
  </div>

  <div class="field">
    <%= form.label :via %>
    <%= form.text_field :via, id: :ticket_via %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<%= render 'shared/flash_notifications' %>
<%= render 'shared/search_bar' %>

<% if @tickets.exists? %>
  <table class="tickets-table">
    <thead>
      <tr>
        <th class="_id">Id</th>
        <th class="url">Url</th>
        <th class="external_id">External Id</th>
        <th class="ticket_type">Ticket Type</th>
        <th class="subject">Subject</th>
        <th class="description">Description</th>
        <th class="priority">Priority</th>
        <th class="status">Status</th>
        <th class="submitter">Submitter Id</th>
        <th class="assignee">Assignee Id</th>
        <th class="organization">Organization Id</th>
        <th class="has_incidents">Has Incidents</th>
        <th class="due_at">Due At</th>
        <th class="via">Via</th>
        <th class="tags">Tags</th>
        <th class="created_at">Created At</th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td class="_id"><%= ticket._id %></td>
          <td class="url"><%= link_to "url", ticket.url %></td>
          <td class="external_id"><%= ticket.external_id %></td>
          <td class="ticket_type"><%= ticket.ticket_type %></td>
          <td class="subject"><%= ticket.subject %></td>
          <td class="description"><%= ticket.description %></td>
          <td class="priority"><%= ticket.priority %></td>
          <td class="status"><%= ticket.status %></td>
          <td class="submitter"><%= submitter_link ticket %></td>
          <td class="assignee"><%= assignee_link ticket %></td>
          <td class="organization"><%= organization_link ticket %></td>
          <td class="has_incidents"><%= ticket.has_incidents %></td>
          <td class="due_at"><%= ticket.due_at %></td>
          <td class="via"><%= ticket.via %></td>
          <td class="tags"><%= tag_names ticket %></td>
          <td class="created_at"><%= ticket.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <div class="no-records notification alert">
    No tickets available for given input.
  </div>
<% end %>

<br/>
<%= paginate @tickets %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @ticket._id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @ticket.url %>
</p>

<p>
  <strong>External:</strong>
  <%= @ticket.external_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @ticket.ticket_type %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @ticket.subject %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @ticket.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<p>
  <strong>Submitter:</strong>
  <%= @ticket.submitter %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= @ticket.assignee %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @ticket.organization %>
</p>

<p>
  <strong>Has incidents:</strong>
  <%= @ticket.has_incidents %>
</p>

<p>
  <strong>Due at:</strong>
  <%= @ticket.due_at %>
</p>

<p>
  <strong>Via:</strong>
  <%= @ticket.via %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>