config/routes.rb
Rails.application.routes.draw do
  resource :home, only: [:show]

  resources :tickets
  resources :users
  resources :organizations

  root 'homes#show'
end

app/models/organization.rb
class Organization < ApplicationRecord
  include SearchableModel

  has_many :tag_lists, as: :taggable
  has_many :tags, through: :tag_lists

  has_many :organization_domains
  has_many :domains, through: :organization_domains

  has_many :users

  def self.searchable_attributes
    @@_searchable_attributes ||= begin
      non_searchables = ["id", "updated_at", "users_count", "tickets_count"]

      column_names - non_searchables + [TAG_FIELD, DOMAIN_FIELD]
    end
  end

  def self.search_by_domains term
    if term.present?
      term_arr = term.split(",").map { |name| name.strip.upcase }
      domains = Domain.where("UPPER(name) IN (?)", term_arr)

      return none if domains.count != term_arr.compact.count

      where(id: OrganizationDomain.having_all(domains).select(:organization_id))
    else
      where.not(id: OrganizationDomain.select(:organization_id))
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  include Searchable
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.includes(:domains, :tags)
                                 .order(:_id)
                                 .page params[:page]

    @organizations = search @organizations
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:_id, :url, :external_id, :name, :details, :shared_tickets)
    end

    def set_model
      @model = Organization
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper

  def users_link organization
    link_to organization.users_count,  users_path(field: :organization_id, value: organization._id)
  end

  def tickets_link organization
    link_to organization.tickets_count,  tickets_path(field: :organization_id, value: organization._id)
  end

  def domain_names organization
    organization.domains.pluck(:name).join ", "
  end
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :_id %>
    <%= form.text_field :_id, id: :organization__id %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :organization_url %>
  </div>

  <div class="field">
    <%= form.label :external_id %>
    <%= form.text_field :external_id, id: :organization_external_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :organization_name %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_field :details, id: :organization_details %>
  </div>

  <div class="field">
    <%= form.label :shared_tickets %>
    <%= form.text_field :shared_tickets, id: :organization_shared_tickets %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<%= render 'shared/flash_notifications' %>
<%= render 'shared/search_bar' %>

<% if @organizations.exists? %>
  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Url</th>
        <th>External Id</th>
        <th>Name</th>
        <th>Details</th>
        <th>Shared Tickets</th>
        <th>Tags</th>
        <th>Domains</th>
        <th>#Users</th>
        <th>#Tickets</th>
        <th>Created At</th>
      </tr>
    </thead>

    <tbody>
      <% @organizations.each do |organization| %>
        <tr>
          <td><%= organization._id %></td>
          <td><%= link_to :url, organization.url %></td>
          <td><%= organization.external_id %></td>
          <td><%= organization.name %></td>
          <td><%= organization.details %></td>
          <td><%= organization.shared_tickets %></td>
          <td><%= tag_names organization %></td>
          <td><%= domain_names organization %></td>
          <td><%= users_link organization %></td>
          <td><%= tickets_link organization %></td>
          <td><%= organization.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-records notification alert">
    No organizations available for given input.
  </div>
<% end %>

<br/>
<%= paginate @organizations %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @organization._id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @organization.url %>
</p>

<p>
  <strong>External:</strong>
  <%= @organization.external_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @organization.details %>
</p>

<p>
  <strong>Shared tickets:</strong>
  <%= @organization.shared_tickets %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>